name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 10.0.2
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/share_plus
topics:
  - share
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FPPSharePlusPlugin
      linux:
        dartPluginClass: SharePlusLinuxPlugin
      macos:
        pluginClass: SharePlusMacosPlugin
      web:
        pluginClass: SharePlusWebPlugin
        fileName: src/share_plus_web.dart
      windows:
        dartPluginClass: SharePlusWindowsPlugin
        pluginClass: SharePlusWindowsPluginCApi

dependencies:
  cross_file: any
  meta: any
  mime: any
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  share_plus_platform_interface: any
  file: ">=6.1.4 <8.0.0"
  url_launcher_web: any
  url_launcher_windows: any
  url_launcher_linux: any
  url_launcher_platform_interface: any
  ffi: any
  web: any

  # win32 is compatible across v4 and v5 for Win32 only (not COM)
  win32: ">=4.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

environment:
  sdk: ">=2.17.5 <3.0.0"
